# apt-secure
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/apt-secure.8.gz
complete -c apt-secure -l no-allow-insecure-repositories --description 'on the command line.'

