# compile_et
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/compile_et.1.gz
complete -c compile_et -l textdomain --description 'option, error messages will be looked up in the specified domain with gettext…'
complete -c compile_et -l localedir --description 'option, the text domain will be bound to the specified locale directory with …'

