# coreutils
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/coreutils.1.gz
complete -c coreutils -l help --description 'display this help and exit.'
complete -c coreutils -l version --description 'output version information and exit.'

