# exo-open
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/exo-open.1.gz
complete -c exo-open -l launch --description 'tries to launch the preferred application for a certain category, optionally …'
complete -c exo-open -s '?' -l help --description '.'
complete -c exo-open -s v -l version --description '.'
complete -c exo-open -l working-directory --description '.'

