# factor
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/factor.1.gz
complete -c factor -l help --description 'display this help and exit.'
complete -c factor -l version --description 'output version information and exit AUTHOR Written by Paul Rubin, Torbjorn Gr…'

