# fsck
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/fsck.minix.8.gz
complete -c fsck -s l -l list --description 'List all filenames.'
complete -c fsck -s r -l repair --description 'Perform interactive repairs.'
complete -c fsck -l auto --description 'Perform automatic repairs.'
complete -c fsck -s s -l super --description 'Output super-block information.'
complete -c fsck -s m -l uncleared --description 'Activate MINIX-like "mode not cleared" warnings.'
complete -c fsck -s f -l force --description 'Force a filesystem check even if the filesystem was marked as valid.'

