# git-stripspace
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/git-stripspace.1.gz
complete -c git-stripspace -s s -l strip-comments --description 'Skip and remove all lines starting with comment character (default #).'
complete -c git-stripspace -s c -l comment-lines --description 'Prepend comment character and blank to each line.'

