# gtk3-widget-factory
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gtk3-widget-factory.1.gz
complete -c gtk3-widget-factory -s h -l help --description 'Show help options.'

