# iconv
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/iconv.1.gz
complete -c iconv -s f -l from-code --description 'Specifies the encoding of the input.'
complete -c iconv -s t -l to-code --description 'Specifies the encoding of the output.'
complete -c iconv -s c --description 'When this option is given, characters that cannot be converted are silently d…'
complete -c iconv -l unicode-subst --description 'When this option is given, Unicode characters that cannot be represented in t…'
complete -c iconv -l byte-subst --description 'When this option is given, bytes in the input that are not valid in the sourc…'
complete -c iconv -l widechar-subst --description 'When this option is given, wide characters in the input that are not valid in…'
complete -c iconv -s s -l silent --description 'When this option is given, error messages about invalid or unconvertible char…'

