# inetd
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/inetd.8.gz
complete -c inetd -s d -l debug --description 'turn on debugging, run in foreground mode.'
complete -c inetd -l environment --description 'pass local and remote socket information in environment variables.'
complete -c inetd -s p -l pidfile --description 'override pidfile (default: "/usr/local/var/run/inetd. pid").'
complete -c inetd -l resolve --description 'resolve IP addresses when setting environment variables (see --environment).'
complete -c inetd -s R -l rate --description 'maximum invocation rate (per minute).'
complete -c inetd -s '?' -l help --description 'give this help list.'
complete -c inetd -l usage --description 'give a short usage message.'
complete -c inetd -s V -l version --description 'print program version.'

