# isosize
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/isosize.8.gz
complete -c isosize -s x -l sectors --description 'Show the block count and block size in human-readable form.'
complete -c isosize -s d -l divisor --description 'Only has an effect when.'

