# kill
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/kill.1.gz
complete -c kill -s l -l list --description 'list signal names, or convert signal names to/from numbers.'
complete -c kill -s t -l table --description 'print a table of signal information.'
complete -c kill -l help --description 'display this help and exit.'
complete -c kill -s s -l signal -o SIGNAL --description 'specify the name or number of the signal to be sent.'
complete -c kill -l version --description 'output version information and exit.'

