# ktutil
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/ktutil.1.gz
complete -c ktutil -s k -s e -s f -s s --description 'Add principal to keylist using key or password.'

