# kvno
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/kvno.1.gz
complete -c kvno -s c --description 'Specifies the name of a credentials cache to use (if not the default).'
complete -c kvno -s e --description 'Specifies the enctype which will be requested for the session key of all the …'
complete -c kvno -s k --description 'Decrypt the acquired tickets using keytab to confirm their validity.'
complete -c kvno -s q --description 'Suppress printing output when successful.'
complete -c kvno -s u --description 'Use the unknown name type in requested service principal names.'
complete -c kvno -s P --description 'Specifies that the service1 service2 .'
complete -c kvno -s S --description 'Specifies that the service1 service2 .'
complete -c kvno -s I --description 'Specifies that protocol transition (S4U2Self) is to be used to acquire a tick…'
complete -c kvno -s U --description 'Same as -I, but treats for_user as an enterprise name.'
complete -c kvno -s F --description 'Specifies that protocol transition is to be used, identifying the client prin…'
complete -c kvno -l cached-only --description 'Only retrieve credentials already present in the cache, not from the KDC.'
complete -c kvno -l no-store --description 'Do not store retrieved credentials in the cache.'
complete -c kvno -l out-cache --description 'Initialize ccache and store all retrieved credentials into it.'
complete -c kvno -l u2u --description 'Requests a user-to-user ticket.'

