# logger
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/logger.1.gz
complete -c logger -s 4 -l ipv4 --description 'use IPv4 for logging to host.'
complete -c logger -s 6 -l ipv6 --description 'use IPv6 with a host target.'
complete -c logger -s f -l file --description 'log the content of FILE.'
complete -c logger -s h -l host --description 'log to HOST instead of to the default \\,/dev/log\\/.'
complete -c logger -s i -l id --description 'log the process id with every line.'
complete -c logger -s p -l priority --description 'log with priority PRI.'
complete -c logger -s s -l stderr --description 'copy the message to stderr.'
complete -c logger -s S -l source --description 'set source IP address.'
complete -c logger -s t -l tag --description 'prepend every line with TAG.'
complete -c logger -s u -l unix --description 'log to UNIX socket SOCK instead of \\,/dev/log\\/.'
complete -c logger -s '?' -l help --description 'give this help list.'
complete -c logger -l usage --description 'give a short usage message.'
complete -c logger -s V -l version --description 'print program version.'

