# soelim
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/soelim.1.gz
complete -c soelim -s C --description 'Recognise . so when not followed by a space character.'
complete -c soelim -s r --description 'Compatibility with GNU groff\'s soelim soelim (does nothing).'
complete -c soelim -s t --description 'Compatibility with GNU groff\'s soelim soelim (does nothing).'
complete -c soelim -s v --description 'Compatibility with GNU groff\'s soelim soelim (does nothing).'
complete -c soelim -s I --description 'This option specify directories where soelim searches for files (both those o…'

