# tftp
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/tftp.1.gz
complete -c tftp -s v -l verbose --description 'verbose output.'
complete -c tftp -s '?' -l help --description 'give this help list.'
complete -c tftp -l usage --description 'give a short usage message.'
complete -c tftp -s V -l version --description 'print program version AUTHOR Written by many authors.'

