# tftpd
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man8/tftpd.8.gz
complete -c tftpd -s l -l logging --description 'enable logging.'
complete -c tftpd -s n -l nonexistent --description 'supress negative acknowledgement of requests for nonexistent relative filenam…'
complete -c tftpd -s g -l group --description 'set explicit group of process owner, used with \'-s\'.'
complete -c tftpd -s s -l secure-dir --description 'change root directory to DIR before searching and serving content.'
complete -c tftpd -s u -l user --description 'set name of process owner, used with \'-s\' and defaults to \'nobody\'.'
complete -c tftpd -s '?' -l help --description 'give this help list.'
complete -c tftpd -l usage --description 'give a short usage message.'
complete -c tftpd -s V -l version --description 'print program version.'

