# Thunar
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/Thunar.1.gz
complete -c Thunar -l bulk-rename --description 'option is specified no file managers windows will be opened, but instead the …'
complete -c Thunar -s '?' -l help --description '.'
complete -c Thunar -s V -l version --description '.'
complete -c Thunar -s B --description '.'
complete -c Thunar -l daemon --description '.'
complete -c Thunar -l display --description '.'
complete -c Thunar -s q -l quit --description '.'

