# vncconfig
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/vncconfig.1.gz
complete -c vncconfig -o connect --description 'Tells an Xvnc server to make a "reverse" connection to a listening VNC viewer…'
complete -c vncconfig -o disconnect --description 'This causes Xvnc to disconnect from all viewers so that the VNC desktop is no…'
complete -c vncconfig -o list --description 'Lists all the parameters supported by Xvnc.'
complete -c vncconfig -o get --description 'Prints the current value of the given Xvnc parameter.'
complete -c vncconfig -o nowin --description 'wish to clutter the desktop with the settings window - alternatively the.'
complete -c vncconfig -o iconic --description '.'
complete -c vncconfig -o desc --description 'Prints a short description of the given Xvnc parameter.'
complete -c vncconfig -o set --description '.'
complete -c vncconfig -l param --description '.'
complete -c vncconfig -o display --description 'Specifies the Xvnc server to control.'

