# vncpasswd
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/vncpasswd.1.gz
complete -c vncpasswd -o rfbauth --description 'use via the -passwd option.'
complete -c vncpasswd -s f --description 'Filter mode.'

