# whoami
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/whoami.1.gz
complete -c whoami -l help --description 'display this help and exit.'
complete -c whoami -l version --description 'output version information and exit AUTHOR Written by Richard Mlynarik.'

