# xfdesktop
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/xfdesktop.1.gz
complete -c xfdesktop -s h -l help --description 'Show help options.'
complete -c xfdesktop -l help-all --description 'Show all help options.'
complete -c xfdesktop -l help-gtk --description 'Show GTK+ Options.'
complete -c xfdesktop -l help-sm-client --description 'Show session management options  . SS APPLICATION OPTIONS:.'
complete -c xfdesktop -s V -l version --description 'Display version information.'
complete -c xfdesktop -s R -l reload --description 'Causes an already-running instance of xfdesktop to reload all its settings an…'
complete -c xfdesktop -s N -l next --description 'Causes an already-running instance of xfdesktop to advance to the next wallpa…'
complete -c xfdesktop -s M -l menu --description 'Causes an already-running instance of xfdesktop to pop up the applications me…'
complete -c xfdesktop -s W -l windowlist --description 'Causes an already-running instance of xfdesktop to pop up the window list men…'
complete -c xfdesktop -s A -l arrange --description 'Automatically arrange all the icons on the desktop.'
complete -c xfdesktop -s D -l disable-wm-check --description 'Do not wait for a window manager on startup.'
complete -c xfdesktop -s e -l enable-debug --description 'Enable debug messages.'
complete -c xfdesktop -s d -l disable-debug --description 'Disable debug messages.'
complete -c xfdesktop -s Q -l quit --description 'Cause xfdesktop to quit.'
complete -c xfdesktop -l display --description 'X display to use.'

